GET  http://localhost:3000/cursos
###

POST http://localhost:3000/cursos HTTP/1.1
Content-Type: application/json

    {"id":"1",
     "employee_name":"Tiger Nixon",
     "employee_salary":"320800",
     "employee_age":"61",
     "profile_image":""
    },


###
PUT http://localhost:3000/cursos HTTP/1.1
Content-Type: application/json

    {   
     "employee_name":"Tiger Nixon...",
     "employee_salary":"320800",
     "employee_age":"61",
     "profile_image":""
    }

###
DELETE  http://localhost:3000/cursos HTTP/1.1
Content-Type: application/json

   { "id":"1",
     "employee_name":"Tiger Nixon",
     "employee_salary":"320800",
     "employee_age":"61",
     "profile_image":""
    }
}